/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.quanly.baocao;

import dao.ThongKeDAO;
import helper.DateHelper;
import helper.DialogHelper;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.text.DecimalFormat;

/**
 *
 * @author Administrator
 */
public class BaoCaoTaiChinhJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BaoCaoTaiChinhJFrame
     */
    public BaoCaoTaiChinhJFrame() {
        initComponents();
        inIt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg_ChonThoiGian = new javax.swing.ButtonGroup();
        pnl_CotTrai = new javax.swing.JPanel();
        lbl_LocTheoThoiGian = new javax.swing.JLabel();
        rad_HomNay = new javax.swing.JRadioButton();
        rad_TuanNay = new javax.swing.JRadioButton();
        rad_ThangNay = new javax.swing.JRadioButton();
        rad_QuyNay = new javax.swing.JRadioButton();
        rad_NamNay = new javax.swing.JRadioButton();
        rad_Khac = new javax.swing.JRadioButton();
        dat_TuNgay = new com.toedter.calendar.JDateChooser();
        dat_DenNgay = new com.toedter.calendar.JDateChooser();
        lbl_XuatFile = new javax.swing.JLabel();
        pnl_CotPhai = new javax.swing.JPanel();
        lbl_TenBaoCao = new javax.swing.JLabel();
        lbl_NgayThongKe = new javax.swing.JLabel();
        lbl_NgayTao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_BangBaoCao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BÁO CÁO TÀI CHÍNH");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        pnl_CotTrai.setBackground(new java.awt.Color(255, 255, 255));

        lbl_LocTheoThoiGian.setBackground(new java.awt.Color(102, 102, 255));
        lbl_LocTheoThoiGian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_LocTheoThoiGian.setForeground(new java.awt.Color(255, 255, 255));
        lbl_LocTheoThoiGian.setText("   LỌC THEO THỜI GIAN");
        lbl_LocTheoThoiGian.setOpaque(true);

        btg_ChonThoiGian.add(rad_HomNay);
        rad_HomNay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_HomNay.setText("Hôm nay");
        rad_HomNay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_HomNayItemStateChanged(evt);
            }
        });

        btg_ChonThoiGian.add(rad_TuanNay);
        rad_TuanNay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_TuanNay.setText("Tuần này");

        btg_ChonThoiGian.add(rad_ThangNay);
        rad_ThangNay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_ThangNay.setSelected(true);
        rad_ThangNay.setText("Tháng này");
        rad_ThangNay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_ThangNayItemStateChanged(evt);
            }
        });

        btg_ChonThoiGian.add(rad_QuyNay);
        rad_QuyNay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_QuyNay.setText("Quý này");

        btg_ChonThoiGian.add(rad_NamNay);
        rad_NamNay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_NamNay.setText("Năm này");
        rad_NamNay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_NamNayItemStateChanged(evt);
            }
        });
        rad_NamNay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_NamNayActionPerformed(evt);
            }
        });

        btg_ChonThoiGian.add(rad_Khac);
        rad_Khac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_Khac.setText("Khác");
        rad_Khac.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rad_KhacStateChanged(evt);
            }
        });

        dat_TuNgay.setBackground(new java.awt.Color(255, 255, 255));
        dat_TuNgay.setDateFormatString("dd/MM/yyyy");
        dat_TuNgay.setEnabled(false);
        dat_TuNgay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dat_DenNgay.setBackground(new java.awt.Color(255, 255, 255));
        dat_DenNgay.setDateFormatString("dd/MM/yyyy");
        dat_DenNgay.setEnabled(false);
        dat_DenNgay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_XuatFile.setBackground(new java.awt.Color(0, 51, 153));
        lbl_XuatFile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_XuatFile.setForeground(new java.awt.Color(255, 255, 255));
        lbl_XuatFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_XuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconExcel.png"))); // NOI18N
        lbl_XuatFile.setText("Xuất file");
        lbl_XuatFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 102)));
        lbl_XuatFile.setOpaque(true);
        lbl_XuatFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_XuatFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_XuatFileMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_CotTraiLayout = new javax.swing.GroupLayout(pnl_CotTrai);
        pnl_CotTrai.setLayout(pnl_CotTraiLayout);
        pnl_CotTraiLayout.setHorizontalGroup(
            pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_LocTheoThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                .addGroup(pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad_Khac)
                            .addComponent(rad_TuanNay)
                            .addComponent(rad_HomNay)
                            .addComponent(rad_ThangNay)
                            .addComponent(rad_QuyNay)
                            .addComponent(rad_NamNay)))
                    .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lbl_XuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CotTraiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dat_TuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(dat_DenNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        pnl_CotTraiLayout.setVerticalGroup(
            pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                .addComponent(lbl_LocTheoThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_HomNay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_TuanNay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_ThangNay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_QuyNay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_NamNay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_Khac)
                .addGap(18, 18, 18)
                .addComponent(dat_TuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dat_DenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_XuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 368, Short.MAX_VALUE))
        );

        lbl_TenBaoCao.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lbl_TenBaoCao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TenBaoCao.setText("Báo cáo kết quả kinh doanh");

        lbl_NgayThongKe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NgayThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NgayThongKe.setText("Từ ngày ............... đến ngày ...............");

        lbl_NgayTao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NgayTao.setText("Ngày tạo: ...............");

        tbl_BangBaoCao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_BangBaoCao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1. Doanh thu bán hàng", null},
                {"2. Các khoản giảm trừ", null},
                {"      Huỷ hàng", null},
                {"3. Doanh thu thuần (1-2)", null},
                {"4. Giá vốn hàng bán", null},
                {"5. Lợi nhuận gộp (3-4)", null},
                {"6. Các khoản thu", null},
                {"7. Các khoản chi", null},
                {"8. Tổng lợi nhuận kinh doanh (5+6-7)", null}
            },
            new String [] {
                "Diễn giải", "Tổng cộng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_BangBaoCao.setRowHeight(35);
        tbl_BangBaoCao.setRowMargin(3);
        jScrollPane1.setViewportView(tbl_BangBaoCao);

        javax.swing.GroupLayout pnl_CotPhaiLayout = new javax.swing.GroupLayout(pnl_CotPhai);
        pnl_CotPhai.setLayout(pnl_CotPhaiLayout);
        pnl_CotPhaiLayout.setHorizontalGroup(
            pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TenBaoCao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NgayThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                        .addComponent(lbl_NgayTao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_CotPhaiLayout.setVerticalGroup(
            pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_TenBaoCao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_NgayThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_NgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_CotTrai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_CotPhai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_CotTrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_CotPhai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rad_NamNayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_NamNayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_NamNayActionPerformed

    private void rad_KhacStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rad_KhacStateChanged
        // TODO add your handling code here:
        if(rad_Khac.isSelected()){
            dat_TuNgay.setEnabled(true);
            dat_DenNgay.setEnabled(true);
        }        
        else
        {
            dat_TuNgay.setEnabled(false);
            dat_DenNgay.setEnabled(false);
        }        
    }//GEN-LAST:event_rad_KhacStateChanged

    private void lbl_XuatFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_XuatFileMouseExited
        // TODO add your handling code here:
        lbl_XuatFile.setBackground(new Color(0,51,153));
        lbl_XuatFile.setForeground(Color.white);
    }//GEN-LAST:event_lbl_XuatFileMouseExited

    private void lbl_XuatFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_XuatFileMouseEntered
        // TODO add your handling code here:
        lbl_XuatFile.setBackground(Color.yellow);
        lbl_XuatFile.setForeground(Color.blue);
        lbl_XuatFile.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbl_XuatFileMouseEntered

    private void rad_ThangNayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_ThangNayItemStateChanged
        // TODO add your handling code here:
        if (rad_ThangNay.isSelected()) {
            bcKetQuaKDThang();
        }
    }//GEN-LAST:event_rad_ThangNayItemStateChanged

    private void rad_NamNayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_NamNayItemStateChanged
        // TODO add your handling code here:
        if (rad_NamNay.isSelected()) {
            bcKetQuaKDNam();
        }
    }//GEN-LAST:event_rad_NamNayItemStateChanged

    private void rad_HomNayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_HomNayItemStateChanged
        // TODO add your handling code here:
        if (rad_HomNay.isSelected()) {
            bcKetQuaKDNgay();
        }
    }//GEN-LAST:event_rad_HomNayItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCaoTaiChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCaoTaiChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCaoTaiChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCaoTaiChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCaoTaiChinhJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg_ChonThoiGian;
    private com.toedter.calendar.JDateChooser dat_DenNgay;
    private com.toedter.calendar.JDateChooser dat_TuNgay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_LocTheoThoiGian;
    private javax.swing.JLabel lbl_NgayTao;
    private javax.swing.JLabel lbl_NgayThongKe;
    private javax.swing.JLabel lbl_TenBaoCao;
    private javax.swing.JLabel lbl_XuatFile;
    private javax.swing.JPanel pnl_CotPhai;
    private javax.swing.JPanel pnl_CotTrai;
    private javax.swing.JRadioButton rad_HomNay;
    private javax.swing.JRadioButton rad_Khac;
    private javax.swing.JRadioButton rad_NamNay;
    private javax.swing.JRadioButton rad_QuyNay;
    private javax.swing.JRadioButton rad_ThangNay;
    private javax.swing.JRadioButton rad_TuanNay;
    private javax.swing.JTable tbl_BangBaoCao;
    // End of variables declaration//GEN-END:variables

    ThongKeDAO TKDAO = new ThongKeDAO();
    
    DecimalFormat dcf = new DecimalFormat("###,###,###.###");
    
    /*
     * Hàm khởi tạo các giá trị ban đầu cho JFrame
     */
    void inIt() {
        setTitle("Báo cáo tài chính");
        setResizable(false);
        setLocationRelativeTo(null);
        bcKetQuaKDThang();
    }
    
    /*
     * Hàm báo cáo kết quả kinh doanh tháng
     */
    void bcKetQuaKDThang() {
        String NgayHienTai = DateHelper.toString(DateHelper.now(), "dd-MM-yyyy");
        String Thang = NgayHienTai.substring(3, 5);
        String Nam = NgayHienTai.substring(6, 10);
        String NgayDauThang = Nam + "-" + Thang + "-01";
        String NgayCuoiThang = "";
        switch (Thang) {
            case "01":
            case "03": 
            case "05": 
            case "07": 
            case "08": 
            case "10": 
            case "12":
                NgayCuoiThang = Nam + "-" + Thang + "-31";
                break;
            case "04": 
            case "06": 
            case "09": 
            case "11": 
                NgayCuoiThang = Nam + "-" + Thang + "-30";
                break;
            case "02": 
                if (DateHelper.xetNamNhuan(Integer.parseInt(Nam))) {
                    NgayCuoiThang = Nam + "-" + Thang + "-29";
                }
                else 
                    NgayCuoiThang = Nam + "-" + Thang + "-28";
                break;
        }
        lbl_NgayThongKe.setText("Thống kê tháng: " + Thang + "-" + Nam);
        lbl_NgayTao.setText("Ngày tạo: " + NgayHienTai);
        try {
            double DoanhThu = TKDAO.tinhDoanhThuTrongThang();    
            double GiaVonHangBan = TKDAO.tinhGiaVonHangBan(NgayDauThang, NgayCuoiThang);
            double LoiNhuanGop = DoanhThu - GiaVonHangBan;
            tbl_BangBaoCao.setValueAt(dcf.format(DoanhThu), 0, 1);
            tbl_BangBaoCao.setValueAt(0, 2, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(DoanhThu), 3, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(GiaVonHangBan), 4, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(LoiNhuanGop), 5, 1);
            tbl_BangBaoCao.setValueAt(0, 6, 1);
            tbl_BangBaoCao.setValueAt(0, 7, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(LoiNhuanGop), 8, 1);
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }
    
    /*
     * Hàm báo cáo kết quả kinh doanh năm
     */
    void bcKetQuaKDNam() {
        String NgayHienTai = DateHelper.toString(DateHelper.now(), "dd-MM-yyyy");
        String Nam = NgayHienTai.substring(6, 10);
        String NgayDauNam = Nam + "-01-01";
        String NgayCuoiNam = Nam + "-12-31";
        
        lbl_NgayThongKe.setText("Thống kê năm: " + Nam);
        lbl_NgayTao.setText("Ngày tạo: " + NgayHienTai);
        try {
            double DoanhThu = TKDAO.tinhDoanhThuTrongNam();    
            double GiaVonHangBan = TKDAO.tinhGiaVonHangBan(NgayDauNam, NgayCuoiNam);
            double LoiNhuanGop = DoanhThu - GiaVonHangBan;
            tbl_BangBaoCao.setValueAt(dcf.format(DoanhThu), 0, 1);
            tbl_BangBaoCao.setValueAt(0, 2, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(DoanhThu), 3, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(GiaVonHangBan), 4, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(LoiNhuanGop), 5, 1);
            tbl_BangBaoCao.setValueAt(0, 6, 1);
            tbl_BangBaoCao.setValueAt(0, 7, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(LoiNhuanGop), 8, 1);
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }
    
    /*
     * Hàm báo cáo kết quả kinh hôm nay
     */
    void bcKetQuaKDNgay() {
        String NgayHienTai = DateHelper.toString(DateHelper.now(), "dd-MM-yyyy");
        lbl_NgayThongKe.setText("Thống kê ngày: " + NgayHienTai);
        lbl_NgayTao.setText("Ngày tạo: " + NgayHienTai);
        try {
            double DoanhThu = TKDAO.tinhDoanhThuTrongNgay();    
            double GiaVonHangBan = TKDAO.tinhGiaVonHangBan(DateHelper.toString(DateHelper.now(), "yyyy-MM-dd"), DateHelper.toString(DateHelper.now(), "yyyy-MM-dd"));
            double LoiNhuanGop = DoanhThu - GiaVonHangBan;
            tbl_BangBaoCao.setValueAt(dcf.format(DoanhThu), 0, 1);
            tbl_BangBaoCao.setValueAt(0, 2, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(DoanhThu), 3, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(GiaVonHangBan), 4, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(LoiNhuanGop), 5, 1);
            tbl_BangBaoCao.setValueAt(0, 6, 1);
            tbl_BangBaoCao.setValueAt(0, 7, 1);
            tbl_BangBaoCao.setValueAt(dcf.format(LoiNhuanGop), 8, 1);
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }
    
}