/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import AppPackage.AnimationClass;
import dao.NguoiDungDAO;
import helper.DialogHelper;
import helper.ShareHelper;
import java.awt.Cursor;
import java.awt.Dimension;
import model.NguoiDung;
import ui.banhang.BanHangJFrame;
import ui.quanly.MainQuanLyJFrame;

/**
 *
 * @author Administrator
 */
public class DangNhapJFrame extends javax.swing.JFrame {

    public DangNhapJFrame() {
        initComponents();
        inIt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Khung = new javax.swing.JPanel();
        pnl_DangNhap = new javax.swing.JPanel();
        lbl_DangNhapPhanMem = new javax.swing.JLabel();
        lbl_SuperSALESText = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        lbl_ThongBao = new javax.swing.JLabel();
        lbl_QuenMatKhau = new javax.swing.JLabel();
        txt_MatKhau = new javax.swing.JPasswordField();
        btn_QuanLy = new javax.swing.JButton();
        btn_BanHang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_AnhSlide1 = new javax.swing.JLabel();
        pnl_TrangThai = new javax.swing.JPanel();
        lbl_CopyRightText = new javax.swing.JLabel();
        lbl_Thoat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHẦN MỀM QUẢN LÝ BÁN HÀNG - SuperSALES");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));

        pnl_Khung.setMaximumSize(new java.awt.Dimension(1366, 768));
        pnl_Khung.setMinimumSize(new java.awt.Dimension(1366, 768));
        pnl_Khung.setLayout(null);

        pnl_DangNhap.setBackground(new java.awt.Color(255, 255, 255));
        pnl_DangNhap.setForeground(new java.awt.Color(255, 255, 255));
        pnl_DangNhap.setMinimumSize(new java.awt.Dimension(400, 400));
        pnl_DangNhap.setPreferredSize(new java.awt.Dimension(400, 400));

        lbl_DangNhapPhanMem.setBackground(new java.awt.Color(204, 204, 204));
        lbl_DangNhapPhanMem.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_DangNhapPhanMem.setForeground(new java.awt.Color(0, 0, 255));
        lbl_DangNhapPhanMem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_DangNhapPhanMem.setText("ĐĂNG NHẬP");

        lbl_SuperSALESText.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_SuperSALESText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_SuperSALESText.setText("<html> </font>Hệ thống quản lí cửa hàng</html>");

        txtTenDangNhap.setBackground(new java.awt.Color(204, 255, 255));
        txtTenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_ThongBao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ThongBao.setForeground(new java.awt.Color(255, 0, 0));
        lbl_ThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl_QuenMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_QuenMatKhau.setForeground(new java.awt.Color(0, 0, 255));
        lbl_QuenMatKhau.setText("Quên mật khẩu?");

        txt_MatKhau.setBackground(new java.awt.Color(204, 255, 255));
        txt_MatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_MatKhau.setMinimumSize(new java.awt.Dimension(6, 35));
        txt_MatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatKhauActionPerformed(evt);
            }
        });

        btn_QuanLy.setBackground(new java.awt.Color(204, 0, 0));
        btn_QuanLy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_QuanLy.setForeground(new java.awt.Color(255, 51, 51));
        btn_QuanLy.setText("QUẢN LÝ");
        btn_QuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyActionPerformed(evt);
            }
        });

        btn_BanHang.setBackground(new java.awt.Color(0, 0, 255));
        btn_BanHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_BanHang.setForeground(new java.awt.Color(0, 0, 255));
        btn_BanHang.setText("BÁN HÀNG");
        btn_BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BanHangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("USERNAME:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("PASSWORD:");

        javax.swing.GroupLayout pnl_DangNhapLayout = new javax.swing.GroupLayout(pnl_DangNhap);
        pnl_DangNhap.setLayout(pnl_DangNhapLayout);
        pnl_DangNhapLayout.setHorizontalGroup(
            pnl_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DangNhapLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnl_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_ThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_SuperSALESText)
                    .addComponent(lbl_DangNhapPhanMem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(pnl_DangNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_DangNhapLayout.createSequentialGroup()
                        .addComponent(lbl_QuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_DangNhapLayout.createSequentialGroup()
                        .addGroup(pnl_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(pnl_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                            .addComponent(txt_MatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnl_DangNhapLayout.createSequentialGroup()
                                .addComponent(btn_QuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))))
                .addContainerGap())
        );
        pnl_DangNhapLayout.setVerticalGroup(
            pnl_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DangNhapLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_DangNhapPhanMem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_SuperSALESText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pnl_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(pnl_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_QuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_QuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnl_Khung.add(pnl_DangNhap);
        pnl_DangNhap.setBounds(440, 120, 600, 390);

        lbl_AnhSlide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Untitled-2.jpg"))); // NOI18N
        pnl_Khung.add(lbl_AnhSlide1);
        lbl_AnhSlide1.setBounds(-30, 0, 1366, 720);

        pnl_TrangThai.setBackground(new java.awt.Color(0, 204, 102));
        pnl_TrangThai.setMaximumSize(new java.awt.Dimension(1366, 50));
        pnl_TrangThai.setMinimumSize(new java.awt.Dimension(1366, 50));
        pnl_TrangThai.setPreferredSize(new java.awt.Dimension(1366, 50));

        lbl_CopyRightText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_CopyRightText.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CopyRightText.setText("Hệ thống quản lí shop bán quần áo - Dự Án 1 - Nhóm 8");

        lbl_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit.png"))); // NOI18N
        lbl_Thoat.setToolTipText("Thoát chương trình");
        lbl_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ThoatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ThoatMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnl_TrangThaiLayout = new javax.swing.GroupLayout(pnl_TrangThai);
        pnl_TrangThai.setLayout(pnl_TrangThaiLayout);
        pnl_TrangThaiLayout.setHorizontalGroup(
            pnl_TrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TrangThaiLayout.createSequentialGroup()
                .addContainerGap(468, Short.MAX_VALUE)
                .addComponent(lbl_CopyRightText, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290)
                .addComponent(lbl_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        pnl_TrangThaiLayout.setVerticalGroup(
            pnl_TrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TrangThaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_CopyRightText, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lbl_Thoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Khung.add(pnl_TrangThai);
        pnl_TrangThai.setBounds(0, 720, 1340, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_Khung, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_Khung, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_ThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThoatMouseEntered
        // TODO add your handling code here:
        lbl_Thoat.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbl_ThoatMouseEntered

    private void lbl_ThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThoatMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_ThoatMouseClicked

    private void btn_QuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyActionPerformed
        // TODO add your handling code here:
        dangNhap(1);
    }//GEN-LAST:event_btn_QuanLyActionPerformed

    private void btn_BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BanHangActionPerformed
        // TODO add your handling code here:
        dangNhap(2);
    }//GEN-LAST:event_btn_BanHangActionPerformed

    private void txt_MatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BanHang;
    private javax.swing.JButton btn_QuanLy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_AnhSlide1;
    private javax.swing.JLabel lbl_CopyRightText;
    private javax.swing.JLabel lbl_DangNhapPhanMem;
    private javax.swing.JLabel lbl_QuenMatKhau;
    private javax.swing.JLabel lbl_SuperSALESText;
    private javax.swing.JLabel lbl_Thoat;
    private javax.swing.JLabel lbl_ThongBao;
    private javax.swing.JPanel pnl_DangNhap;
    private javax.swing.JPanel pnl_Khung;
    private javax.swing.JPanel pnl_TrangThai;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JPasswordField txt_MatKhau;
    // End of variables declaration//GEN-END:variables

    AnimationClass AC = new AnimationClass();
    NguoiDungDAO NguoiDungDAO = new NguoiDungDAO();
    
    void inIt() {
        setTitle("Đăng nhập");
        setResizable(false);
        setLocationRelativeTo(null);

    }


    public void dangNhap(int chon) {
        String TenDangNhap = txtTenDangNhap.getText();
        String MatKhau = new String(txt_MatKhau.getPassword());
        try {
            NguoiDung ND = NguoiDungDAO.timTenDangNhap(TenDangNhap);
            if (ND != null) {
                if (ND.getTrangThai()) {
                    String matKhau2 = ND.getMatKhau();
                    if (MatKhau.equals(matKhau2)) {
                        int vaiTro = ND.getVaiTro();
                        if (chon == 1 && vaiTro == 1) {
                            lbl_ThongBao.setText("");
                            ShareHelper.NguoiDung = ND;
                            DialogHelper.alert(this, "Đăng nhập thành công!");
                            this.dispose();
                            new MainQuanLyJFrame().setVisible(true);
                        } else if (chon == 1 && vaiTro == 0) {
                            lbl_ThongBao.setText("Bạn không được cấp quyền sử dụng chức năng này");
                        } else if (chon == 2) {
                            lbl_ThongBao.setText("");
                            ShareHelper.NguoiDung = ND;
                            DialogHelper.alert(this, "Đăng nhập thành công!");
                            this.dispose();
                            new BanHangJFrame().setVisible(true);
                        }
                    } else {
                        DialogHelper.alert(this, "Sai mật khẩu");
                    }
                }
                else {
                    DialogHelper.alert(this, "Người dùng đang bị khoá tài khoản");
                }
            } else {
                DialogHelper.alert(this, "Sai tên đăng nhập");
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }
}
