/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.quanly;

import dao.HoaDonDAO;
import dao.SanPhamDAO;
import dao.ThongKeDAO;
import helper.DateHelper;
import helper.DialogHelper;
import helper.ShareHelper;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import ui.DangNhapJFrame;
import ui.chung.ThongTinTaiKhoanJFrame;
import ui.quanly.baocao.BaoCaoBanHangJFrame;
import ui.quanly.baocao.BaoCaoKhoHangJFrame;
import ui.quanly.baocao.BaoCaoNhapHangJFrame;
import ui.quanly.baocao.BaoCaoTaiChinhJFrame;
import ui.quanly.doitac.DanhSachKhachHangJFrame;
import ui.quanly.doitac.DanhSachNhaCungCapJFrame;
import ui.quanly.giaodich.DanhSachHoaDonJFrame;
import ui.quanly.giaodich.DanhSachPhieuNhapJFrame;
import ui.quanly.giaodich.XuatHuyHangJFrame;
import ui.quanly.nhanvien.DanhSachNhanVienJFrame;
import ui.quanly.sanpham.CanhBaoHSDJFrame;
import ui.quanly.sanpham.DanhSachSanPhamJFrame;
import ui.quanly.sanpham.KiemKeSanPhamJFrame;

/**
 *
 * @author Administrator
 */
public class MainQuanLyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainQuanLyJFrame
     */
    public MainQuanLyJFrame() {
        initComponents();
        inIt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_TongDonHang = new javax.swing.JPanel();
        lbl_TextTongDonHang = new javax.swing.JLabel();
        lbl_NumTongDonHang = new javax.swing.JLabel();
        pnl_TongDoanhThu = new javax.swing.JPanel();
        lbl_NumTongDoanhThu = new javax.swing.JLabel();
        lbl_TextTongDoanhThu = new javax.swing.JLabel();
        pnl_CanhBaoHSD = new javax.swing.JPanel();
        lbl_NumCanhBao = new javax.swing.JLabel();
        lbl_TextCanhBao = new javax.swing.JLabel();
        pnl_BieuDoThongKe = new javax.swing.JPanel();
        lbl_ThongKeDoanhThu = new javax.swing.JLabel();
        cmb_TuyChonThoiGian = new javax.swing.JComboBox<>();
        pnl_BarChart = new javax.swing.JPanel();
        pnl_SanPhamBanChay = new javax.swing.JPanel();
        lbl_SanPhamBanChay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DanhSachSanPham = new javax.swing.JTable();
        pnl_ThanhTrangThai = new javax.swing.JPanel();
        lbl_TenPhanMem = new javax.swing.JLabel();
        lbl_NgayThangNam = new javax.swing.JLabel();
        lbl_DongHo = new javax.swing.JLabel();
        mnb_MenuQuanLy = new javax.swing.JMenuBar();
        mnu_TaiKhoan = new javax.swing.JMenu();
        mni_ThongTinTaiKhoan = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mni_DangXuat = new javax.swing.JMenuItem();
        mni_Thoat = new javax.swing.JMenuItem();
        mnu_NhanVien = new javax.swing.JMenu();
        mni_QuanLyNhanVien = new javax.swing.JMenuItem();
        mnu_SanPham = new javax.swing.JMenu();
        mni_DanhSachSanPham = new javax.swing.JMenuItem();
        mni_ThietLapGia = new javax.swing.JMenuItem();
        mni_KiemKe = new javax.swing.JMenuItem();
        mni_CanhBaoHSD = new javax.swing.JMenuItem();
        mnu_GiaoDich = new javax.swing.JMenu();
        mni_HoaDon = new javax.swing.JMenuItem();
        mni_NhapHang = new javax.swing.JMenuItem();
        mni_TraHang = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mni_XuatHuyHang = new javax.swing.JMenuItem();
        mnu_DoiTac = new javax.swing.JMenu();
        mni_KhachHang = new javax.swing.JMenuItem();
        mni_NhaCungCap = new javax.swing.JMenuItem();
        mnu_BaoCao = new javax.swing.JMenu();
        mni_BCBanHang = new javax.swing.JMenuItem();
        mni_BCNhapHang = new javax.swing.JMenuItem();
        mni_BCKhoHang = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mni_BCTaiChinh = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ CỬA HÀNG");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        pnl_TongDonHang.setBackground(new java.awt.Color(255, 255, 255));
        pnl_TongDonHang.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(204, 204, 204)));
        pnl_TongDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_TongDonHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_TongDonHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_TongDonHangMouseExited(evt);
            }
        });

        lbl_TextTongDonHang.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lbl_TextTongDonHang.setForeground(new java.awt.Color(204, 0, 0));
        lbl_TextTongDonHang.setText("TỔNG ĐƠN HÀNG");

        lbl_NumTongDonHang.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbl_NumTongDonHang.setForeground(new java.awt.Color(204, 0, 0));
        lbl_NumTongDonHang.setText("000");

        javax.swing.GroupLayout pnl_TongDonHangLayout = new javax.swing.GroupLayout(pnl_TongDonHang);
        pnl_TongDonHang.setLayout(pnl_TongDonHangLayout);
        pnl_TongDonHangLayout.setHorizontalGroup(
            pnl_TongDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TongDonHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_TongDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NumTongDonHang)
                    .addComponent(lbl_TextTongDonHang))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pnl_TongDonHangLayout.setVerticalGroup(
            pnl_TongDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TongDonHangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_TextTongDonHang)
                .addGap(18, 18, 18)
                .addComponent(lbl_NumTongDonHang)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnl_TongDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        pnl_TongDoanhThu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(204, 204, 204)));
        pnl_TongDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_TongDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_TongDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_TongDoanhThuMouseExited(evt);
            }
        });

        lbl_NumTongDoanhThu.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbl_NumTongDoanhThu.setForeground(new java.awt.Color(204, 0, 0));
        lbl_NumTongDoanhThu.setText("000");

        lbl_TextTongDoanhThu.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lbl_TextTongDoanhThu.setForeground(new java.awt.Color(204, 0, 0));
        lbl_TextTongDoanhThu.setText("DOANH THU");

        javax.swing.GroupLayout pnl_TongDoanhThuLayout = new javax.swing.GroupLayout(pnl_TongDoanhThu);
        pnl_TongDoanhThu.setLayout(pnl_TongDoanhThuLayout);
        pnl_TongDoanhThuLayout.setHorizontalGroup(
            pnl_TongDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TongDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_TongDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NumTongDoanhThu)
                    .addComponent(lbl_TextTongDoanhThu))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        pnl_TongDoanhThuLayout.setVerticalGroup(
            pnl_TongDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TongDoanhThuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_TextTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_NumTongDoanhThu)
                .addGap(22, 22, 22))
        );

        pnl_CanhBaoHSD.setBackground(new java.awt.Color(255, 255, 255));
        pnl_CanhBaoHSD.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(204, 204, 204)));
        pnl_CanhBaoHSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_CanhBaoHSDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_CanhBaoHSDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_CanhBaoHSDMouseExited(evt);
            }
        });

        lbl_NumCanhBao.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbl_NumCanhBao.setForeground(new java.awt.Color(204, 0, 0));
        lbl_NumCanhBao.setText("000");

        lbl_TextCanhBao.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lbl_TextCanhBao.setForeground(new java.awt.Color(204, 0, 0));
        lbl_TextCanhBao.setText("SP GẦN HẾT HẠN");

        javax.swing.GroupLayout pnl_CanhBaoHSDLayout = new javax.swing.GroupLayout(pnl_CanhBaoHSD);
        pnl_CanhBaoHSD.setLayout(pnl_CanhBaoHSDLayout);
        pnl_CanhBaoHSDLayout.setHorizontalGroup(
            pnl_CanhBaoHSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CanhBaoHSDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CanhBaoHSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TextCanhBao)
                    .addComponent(lbl_NumCanhBao))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pnl_CanhBaoHSDLayout.setVerticalGroup(
            pnl_CanhBaoHSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CanhBaoHSDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TextCanhBao)
                .addGap(18, 18, 18)
                .addComponent(lbl_NumCanhBao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_BieuDoThongKe.setBackground(new java.awt.Color(255, 255, 255));
        pnl_BieuDoThongKe.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(204, 204, 204)));
        pnl_BieuDoThongKe.setPreferredSize(new java.awt.Dimension(104, 496));

        lbl_ThongKeDoanhThu.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lbl_ThongKeDoanhThu.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ThongKeDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ThongKeDoanhThu.setText("Thống kê doanh thu");

        cmb_TuyChonThoiGian.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_TuyChonThoiGian.setForeground(new java.awt.Color(0, 0, 153));
        cmb_TuyChonThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 ngày", "1 tháng", "3 tháng", "6 tháng", "1 năm" }));

        pnl_BarChart.setBackground(new java.awt.Color(255, 255, 255));
        pnl_BarChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnl_BieuDoThongKeLayout = new javax.swing.GroupLayout(pnl_BieuDoThongKe);
        pnl_BieuDoThongKe.setLayout(pnl_BieuDoThongKeLayout);
        pnl_BieuDoThongKeLayout.setHorizontalGroup(
            pnl_BieuDoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BieuDoThongKeLayout.createSequentialGroup()
                .addGroup(pnl_BieuDoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BieuDoThongKeLayout.createSequentialGroup()
                        .addComponent(lbl_ThongKeDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_TuyChonThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_BieuDoThongKeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnl_BarChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_BieuDoThongKeLayout.setVerticalGroup(
            pnl_BieuDoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BieuDoThongKeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_BieuDoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ThongKeDoanhThu)
                    .addComponent(cmb_TuyChonThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnl_BarChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_SanPhamBanChay.setBackground(new java.awt.Color(255, 255, 255));
        pnl_SanPhamBanChay.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(204, 204, 204)));

        lbl_SanPhamBanChay.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lbl_SanPhamBanChay.setForeground(new java.awt.Color(204, 0, 0));
        lbl_SanPhamBanChay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_SanPhamBanChay.setText("Sản phẩm bán chạy");

        tbl_DanhSachSanPham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_DanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng bán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_DanhSachSanPham.setRowHeight(40);
        tbl_DanhSachSanPham.setRowMargin(3);
        jScrollPane1.setViewportView(tbl_DanhSachSanPham);

        javax.swing.GroupLayout pnl_SanPhamBanChayLayout = new javax.swing.GroupLayout(pnl_SanPhamBanChay);
        pnl_SanPhamBanChay.setLayout(pnl_SanPhamBanChayLayout);
        pnl_SanPhamBanChayLayout.setHorizontalGroup(
            pnl_SanPhamBanChayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SanPhamBanChayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_SanPhamBanChayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_SanPhamBanChay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_SanPhamBanChayLayout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_SanPhamBanChayLayout.setVerticalGroup(
            pnl_SanPhamBanChayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SanPhamBanChayLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_SanPhamBanChay)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_ThanhTrangThai.setBackground(new java.awt.Color(0, 0, 153));
        pnl_ThanhTrangThai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lbl_TenPhanMem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenPhanMem.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TenPhanMem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TenPhanMem.setText("Hệ thống quản lí shop bán quần áo - Dự Án 1 - Nhóm 8");

        lbl_NgayThangNam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_NgayThangNam.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NgayThangNam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_NgayThangNam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconCalendar.png"))); // NOI18N
        lbl_NgayThangNam.setText("dd-MM-yyyy");

        lbl_DongHo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_DongHo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DongHo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_DongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconClock.png"))); // NOI18N
        lbl_DongHo.setText("hh:mm:ss");

        javax.swing.GroupLayout pnl_ThanhTrangThaiLayout = new javax.swing.GroupLayout(pnl_ThanhTrangThai);
        pnl_ThanhTrangThai.setLayout(pnl_ThanhTrangThaiLayout);
        pnl_ThanhTrangThaiLayout.setHorizontalGroup(
            pnl_ThanhTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThanhTrangThaiLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_TenPhanMem, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_NgayThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_DongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnl_ThanhTrangThaiLayout.setVerticalGroup(
            pnl_ThanhTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThanhTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_TenPhanMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_NgayThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbl_DongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mnu_TaiKhoan.setText("Tài khoản");
        mnu_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnu_TaiKhoan.setMargin(new java.awt.Insets(0, 0, 0, 30));

        mni_ThongTinTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_ThongTinTaiKhoan.setText("Thông tin tài khoản");
        mni_ThongTinTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_ThongTinTaiKhoanActionPerformed(evt);
            }
        });
        mnu_TaiKhoan.add(mni_ThongTinTaiKhoan);
        mnu_TaiKhoan.add(jSeparator1);

        mni_DangXuat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_DangXuat.setText("Đăng xuất");
        mni_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_DangXuatActionPerformed(evt);
            }
        });
        mnu_TaiKhoan.add(mni_DangXuat);

        mni_Thoat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_Thoat.setText("Thoát");
        mni_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_ThoatActionPerformed(evt);
            }
        });
        mnu_TaiKhoan.add(mni_Thoat);

        mnb_MenuQuanLy.add(mnu_TaiKhoan);

        mnu_NhanVien.setText("Nhân viên");
        mnu_NhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnu_NhanVien.setMargin(new java.awt.Insets(0, 0, 0, 30));
        mnu_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_NhanVienActionPerformed(evt);
            }
        });

        mni_QuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_QuanLyNhanVien.setText("Quản lý nhân viên");
        mni_QuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_QuanLyNhanVienActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_QuanLyNhanVien);

        mnb_MenuQuanLy.add(mnu_NhanVien);

        mnu_SanPham.setText("Sản phẩm");
        mnu_SanPham.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnu_SanPham.setMargin(new java.awt.Insets(0, 0, 0, 30));

        mni_DanhSachSanPham.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_DanhSachSanPham.setText("Danh sách sản phẩm");
        mni_DanhSachSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_DanhSachSanPhamActionPerformed(evt);
            }
        });
        mnu_SanPham.add(mni_DanhSachSanPham);

        mni_ThietLapGia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_ThietLapGia.setText("Thiết lập giá");
        mnu_SanPham.add(mni_ThietLapGia);

        mni_KiemKe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_KiemKe.setText("Kiểm kê");
        mni_KiemKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_KiemKeActionPerformed(evt);
            }
        });
        mnu_SanPham.add(mni_KiemKe);

        mni_CanhBaoHSD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_CanhBaoHSD.setText("Cảnh báo hết HSD");
        mni_CanhBaoHSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_CanhBaoHSDActionPerformed(evt);
            }
        });
        mnu_SanPham.add(mni_CanhBaoHSD);

        mnb_MenuQuanLy.add(mnu_SanPham);

        mnu_GiaoDich.setText("Giao dịch");
        mnu_GiaoDich.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnu_GiaoDich.setMargin(new java.awt.Insets(0, 0, 0, 30));

        mni_HoaDon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_HoaDon.setText("Hoá đơn");
        mni_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_HoaDonActionPerformed(evt);
            }
        });
        mnu_GiaoDich.add(mni_HoaDon);

        mni_NhapHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_NhapHang.setText("Nhập hàng");
        mni_NhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NhapHangActionPerformed(evt);
            }
        });
        mnu_GiaoDich.add(mni_NhapHang);

        mni_TraHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_TraHang.setText("Trả hàng");
        mnu_GiaoDich.add(mni_TraHang);
        mnu_GiaoDich.add(jSeparator2);

        mni_XuatHuyHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_XuatHuyHang.setText("Xuất huỷ hàng");
        mni_XuatHuyHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_XuatHuyHangActionPerformed(evt);
            }
        });
        mnu_GiaoDich.add(mni_XuatHuyHang);

        mnb_MenuQuanLy.add(mnu_GiaoDich);

        mnu_DoiTac.setText("Đối tác");
        mnu_DoiTac.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnu_DoiTac.setMargin(new java.awt.Insets(0, 0, 0, 30));

        mni_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_KhachHang.setText("Khách hàng");
        mni_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_KhachHangActionPerformed(evt);
            }
        });
        mnu_DoiTac.add(mni_KhachHang);

        mni_NhaCungCap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_NhaCungCap.setText("Nhà cung cấp");
        mni_NhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NhaCungCapActionPerformed(evt);
            }
        });
        mnu_DoiTac.add(mni_NhaCungCap);

        mnb_MenuQuanLy.add(mnu_DoiTac);

        mnu_BaoCao.setText("Báo cáo");
        mnu_BaoCao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnu_BaoCao.setMargin(new java.awt.Insets(0, 0, 0, 30));

        mni_BCBanHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_BCBanHang.setText("Bán hàng");
        mni_BCBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_BCBanHangActionPerformed(evt);
            }
        });
        mnu_BaoCao.add(mni_BCBanHang);

        mni_BCNhapHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_BCNhapHang.setText("Nhập hàng");
        mni_BCNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_BCNhapHangActionPerformed(evt);
            }
        });
        mnu_BaoCao.add(mni_BCNhapHang);

        mni_BCKhoHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_BCKhoHang.setText("Kho hàng");
        mni_BCKhoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_BCKhoHangActionPerformed(evt);
            }
        });
        mnu_BaoCao.add(mni_BCKhoHang);
        mnu_BaoCao.add(jSeparator3);

        mni_BCTaiChinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mni_BCTaiChinh.setText("Tài chính");
        mni_BCTaiChinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_BCTaiChinhActionPerformed(evt);
            }
        });
        mnu_BaoCao.add(mni_BCTaiChinh);

        mnb_MenuQuanLy.add(mnu_BaoCao);

        setJMenuBar(mnb_MenuQuanLy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_BieuDoThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_TongDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_TongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_SanPhamBanChay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_CanhBaoHSD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addComponent(pnl_ThanhTrangThai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnl_TongDoanhThu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_TongDonHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_CanhBaoHSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_BieuDoThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addComponent(pnl_SanPhamBanChay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_ThanhTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_TongDonHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TongDonHangMouseEntered
        // TODO add your handling code here:
        pnl_TongDonHang.setBackground(new Color(252,253,135));
        pnl_TongDonHang.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnl_TongDonHangMouseEntered

    private void pnl_TongDonHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TongDonHangMouseExited
        // TODO add your handling code here:
        pnl_TongDonHang.setBackground(Color.white);
    }//GEN-LAST:event_pnl_TongDonHangMouseExited

    private void pnl_TongDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TongDoanhThuMouseEntered
        // TODO add your handling code here:
        pnl_TongDoanhThu.setBackground(new Color(252,253,135));
        pnl_TongDoanhThu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnl_TongDoanhThuMouseEntered

    private void pnl_TongDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TongDoanhThuMouseExited
        // TODO add your handling code here:
        pnl_TongDoanhThu.setBackground(Color.white);
    }//GEN-LAST:event_pnl_TongDoanhThuMouseExited

    private void pnl_CanhBaoHSDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_CanhBaoHSDMouseEntered
        // TODO add your handling code here:
        pnl_CanhBaoHSD.setBackground(new Color(252,253,135));
        pnl_CanhBaoHSD.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnl_CanhBaoHSDMouseEntered

    private void pnl_CanhBaoHSDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_CanhBaoHSDMouseExited
        // TODO add your handling code here:
        pnl_CanhBaoHSD.setBackground(Color.white);
    }//GEN-LAST:event_pnl_CanhBaoHSDMouseExited

    private void mnu_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_NhanVienActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnu_NhanVienActionPerformed

    private void mni_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_KhachHangActionPerformed
        // TODO add your handling code here:
        new DanhSachKhachHangJFrame().setVisible(true);
    }//GEN-LAST:event_mni_KhachHangActionPerformed

    private void mni_NhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NhaCungCapActionPerformed
        // TODO add your handling code here:
        new DanhSachNhaCungCapJFrame().setVisible(true);
    }//GEN-LAST:event_mni_NhaCungCapActionPerformed

    private void mni_QuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_QuanLyNhanVienActionPerformed
        // TODO add your handling code here:
        new DanhSachNhanVienJFrame().setVisible(true);
    }//GEN-LAST:event_mni_QuanLyNhanVienActionPerformed

    private void mni_KiemKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_KiemKeActionPerformed
        // TODO add your handling code here:
        new KiemKeSanPhamJFrame().setVisible(true);
    }//GEN-LAST:event_mni_KiemKeActionPerformed

    private void mni_XuatHuyHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_XuatHuyHangActionPerformed
        // TODO add your handling code here:
        new XuatHuyHangJFrame().setVisible(true);
    }//GEN-LAST:event_mni_XuatHuyHangActionPerformed

    private void mni_CanhBaoHSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_CanhBaoHSDActionPerformed
        // TODO add your handling code here:
        new CanhBaoHSDJFrame().setVisible(true);
    }//GEN-LAST:event_mni_CanhBaoHSDActionPerformed

    private void mni_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_HoaDonActionPerformed
        // TODO add your handling code here:
        new DanhSachHoaDonJFrame().setVisible(true);
    }//GEN-LAST:event_mni_HoaDonActionPerformed

    private void mni_NhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NhapHangActionPerformed
        // TODO add your handling code here:
        new DanhSachPhieuNhapJFrame().setVisible(true);
    }//GEN-LAST:event_mni_NhapHangActionPerformed

    private void mni_DanhSachSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_DanhSachSanPhamActionPerformed
        // TODO add your handling code here:
        new DanhSachSanPhamJFrame().setVisible(true);
    }//GEN-LAST:event_mni_DanhSachSanPhamActionPerformed

    private void mni_ThongTinTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_ThongTinTaiKhoanActionPerformed
        // TODO add your handling code here:
        new ThongTinTaiKhoanJFrame().setVisible(true);
    }//GEN-LAST:event_mni_ThongTinTaiKhoanActionPerformed

    private void mni_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_DangXuatActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_mni_DangXuatActionPerformed

    private void mni_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_ThoatActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_mni_ThoatActionPerformed

    private void mni_BCBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_BCBanHangActionPerformed
        // TODO add your handling code here:
        new BaoCaoBanHangJFrame().setVisible(true);
    }//GEN-LAST:event_mni_BCBanHangActionPerformed

    private void mni_BCKhoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_BCKhoHangActionPerformed
        // TODO add your handling code here:
        new BaoCaoKhoHangJFrame().setVisible(true);
    }//GEN-LAST:event_mni_BCKhoHangActionPerformed

    private void mni_BCNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_BCNhapHangActionPerformed
        // TODO add your handling code here:
        new BaoCaoNhapHangJFrame().setVisible(true);
    }//GEN-LAST:event_mni_BCNhapHangActionPerformed

    private void mni_BCTaiChinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_BCTaiChinhActionPerformed
        // TODO add your handling code here:
        new BaoCaoTaiChinhJFrame().setVisible(true);
    }//GEN-LAST:event_mni_BCTaiChinhActionPerformed

    private void pnl_TongDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TongDonHangMouseClicked
        // TODO add your handling code here:
        new DanhSachHoaDonJFrame().setVisible(true);
    }//GEN-LAST:event_pnl_TongDonHangMouseClicked

    private void pnl_TongDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TongDoanhThuMouseClicked
        // TODO add your handling code here:
        new BaoCaoTaiChinhJFrame().setVisible(true);
    }//GEN-LAST:event_pnl_TongDoanhThuMouseClicked

    private void pnl_CanhBaoHSDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_CanhBaoHSDMouseClicked
        // TODO add your handling code here:
        new CanhBaoHSDJFrame().setVisible(true);
    }//GEN-LAST:event_pnl_CanhBaoHSDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainQuanLyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_TuyChonThoiGian;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lbl_DongHo;
    private javax.swing.JLabel lbl_NgayThangNam;
    private javax.swing.JLabel lbl_NumCanhBao;
    private javax.swing.JLabel lbl_NumTongDoanhThu;
    private javax.swing.JLabel lbl_NumTongDonHang;
    private javax.swing.JLabel lbl_SanPhamBanChay;
    private javax.swing.JLabel lbl_TenPhanMem;
    private javax.swing.JLabel lbl_TextCanhBao;
    private javax.swing.JLabel lbl_TextTongDoanhThu;
    private javax.swing.JLabel lbl_TextTongDonHang;
    private javax.swing.JLabel lbl_ThongKeDoanhThu;
    private javax.swing.JMenuBar mnb_MenuQuanLy;
    private javax.swing.JMenuItem mni_BCBanHang;
    private javax.swing.JMenuItem mni_BCKhoHang;
    private javax.swing.JMenuItem mni_BCNhapHang;
    private javax.swing.JMenuItem mni_BCTaiChinh;
    private javax.swing.JMenuItem mni_CanhBaoHSD;
    private javax.swing.JMenuItem mni_DangXuat;
    private javax.swing.JMenuItem mni_DanhSachSanPham;
    private javax.swing.JMenuItem mni_HoaDon;
    private javax.swing.JMenuItem mni_KhachHang;
    private javax.swing.JMenuItem mni_KiemKe;
    private javax.swing.JMenuItem mni_NhaCungCap;
    private javax.swing.JMenuItem mni_NhapHang;
    private javax.swing.JMenuItem mni_QuanLyNhanVien;
    private javax.swing.JMenuItem mni_ThietLapGia;
    private javax.swing.JMenuItem mni_Thoat;
    private javax.swing.JMenuItem mni_ThongTinTaiKhoan;
    private javax.swing.JMenuItem mni_TraHang;
    private javax.swing.JMenuItem mni_XuatHuyHang;
    private javax.swing.JMenu mnu_BaoCao;
    private javax.swing.JMenu mnu_DoiTac;
    private javax.swing.JMenu mnu_GiaoDich;
    private javax.swing.JMenu mnu_NhanVien;
    private javax.swing.JMenu mnu_SanPham;
    private javax.swing.JMenu mnu_TaiKhoan;
    private javax.swing.JPanel pnl_BarChart;
    private javax.swing.JPanel pnl_BieuDoThongKe;
    private javax.swing.JPanel pnl_CanhBaoHSD;
    private javax.swing.JPanel pnl_SanPhamBanChay;
    private javax.swing.JPanel pnl_ThanhTrangThai;
    private javax.swing.JPanel pnl_TongDoanhThu;
    private javax.swing.JPanel pnl_TongDonHang;
    private javax.swing.JTable tbl_DanhSachSanPham;
    // End of variables declaration//GEN-END:variables

    ThongKeDAO TKDAO = new ThongKeDAO();
    HoaDonDAO HDDAO = new HoaDonDAO();
    SanPhamDAO SPDAO = new SanPhamDAO();
    
    DecimalFormat dcf = new DecimalFormat("###,###,###");
    
    void inIt() {
        setTitle("Quản lí");
        setResizable(false);
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        startDongHo();
        doThongTin();
        hienBieuDo();
    }
    
    // đồng hồ
    void startDongHo(){
        lbl_NgayThangNam.setText(DateHelper.toString(DateHelper.now(), "dd-MM-yyyy"));
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");
            @Override
            public void actionPerformed(ActionEvent e) {
                lbl_DongHo.setText(format.format(new Date()));
            }
        }).start();
    }
    
    void doThongTin() {
        try {
            double TongDoanhThu = TKDAO.tinhTongDoanhThu();
            int TongDonHang = HDDAO.demHoaDon();
            int SPHetHan = TKDAO.demSanPhamHetHSD();
            lbl_NumTongDoanhThu.setText(dcf.format(TongDoanhThu));
            lbl_NumTongDonHang.setText(TongDonHang+"");
            lbl_NumCanhBao.setText(SPHetHan+"");
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }
    
    // hàm thoái
    void exit(){
        if(DialogHelper.confirm(this, "Bạn muốn thoát chương trình?")){
            System.exit(0);
        }
    }
    
    // đăng xuất
    void logout(){
        if(DialogHelper.confirm(this, "Bạn muốn đăng xuất?")){
            ShareHelper.HoaDonGiaoDich = null;
            ShareHelper.KhachGiaoDich = null;
            ShareHelper.NguoiDung = null;
            this.dispose();
            new DangNhapJFrame().setVisible(true);
        }
    }
    
    
    // Hàm hiển thị biểu đồ thống kê
    
    void hienBieuDo() {
        DefaultCategoryDataset barChartdata = new DefaultCategoryDataset();
        
        barChartdata.setValue(4000000, "Doanh thu", "Tháng 10");
        barChartdata.setValue(5000000, "Doanh thu", "Tháng 11");
        barChartdata.setValue(7000000, "Doanh thu", "Tháng 12");
        
        JFreeChart barChart = ChartFactory.createBarChart("", "", "Doanh thu", barChartdata, PlotOrientation.VERTICAL, false, false, false);
        CategoryPlot plot = barChart.getCategoryPlot();
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setTickUnit(new NumberTickUnit(1000000));
        
        ChartPanel barPanel = new ChartPanel(barChart);
        pnl_BarChart.removeAll();
        pnl_BarChart.add(barPanel, BorderLayout.CENTER);
    }
    
}