/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.quanly.giaodich;

import dao.DonViTinhDAO;
import dao.HoaDonChiTietDAO;
import dao.HoaDonDAO;
import dao.KhachHangDAO;
import dao.NguoiDungDAO;
import dao.NhomHangDAO;
import dao.PhieuHuyChiTietDAO;
import dao.PhieuHuyDAO;
import dao.SanPhamDAO;
import helper.DateHelper;
import helper.DialogHelper;
import helper.jdbcHelper;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.List;
import java.util.TreeMap;
import javax.swing.table.DefaultTableModel;
import model.DonViTinh;
import model.HoaDon;
import model.HoaDonChiTiet;
import model.KhachHang;
import model.PhieuHuyChiTiet;
import model.PhieuHuyHang;
import model.SanPham;

/**
 *
 * @author Admin
 */
public class ChiTietHoaDonJFrame extends javax.swing.JFrame {
    
    private static HoaDon HD;
    
    /**
     * Creates new form ChiTietHoaDonJFrame
     * @param HD - đối tượng hoá đơn truyền từ frame DanhSachHoaDon
     */
    public ChiTietHoaDonJFrame(HoaDon HD) {
        initComponents();
        this.HD = HD;
        inIt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg_LoaiPhieuHuy = new javax.swing.ButtonGroup();
        pnl_CotTrai = new javax.swing.JPanel();
        lbl_TieuDe = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_DanhSachSanPham = new javax.swing.JTable();
        pnl_CotPhai = new javax.swing.JPanel();
        btn_InHoaDon = new javax.swing.JButton();
        lbl_MaHoaDon = new javax.swing.JLabel();
        txt_MaHoaDon = new javax.swing.JTextField();
        txt_TenKhachHang = new javax.swing.JTextField();
        lbl_TenKhachHang = new javax.swing.JLabel();
        txt_NhanVien = new javax.swing.JTextField();
        lbl_NhanVien = new javax.swing.JLabel();
        lbl_NgayBan = new javax.swing.JLabel();
        txt_NgayBan = new javax.swing.JTextField();
        lbl_TongSoLuong = new javax.swing.JLabel();
        txt_TongSoLuong = new javax.swing.JTextField();
        lbl_ThanhTien = new javax.swing.JLabel();
        txt_ThanhTien = new javax.swing.JTextField();
        txt_ChietKhau = new javax.swing.JTextField();
        lbl_ChietKhau = new javax.swing.JLabel();
        lbl_VAT = new javax.swing.JLabel();
        txt_VAT = new javax.swing.JTextField();
        lbl_TongCong = new javax.swing.JLabel();
        txt_TongCong = new javax.swing.JTextField();
        lbl_TienKhachTra = new javax.swing.JLabel();
        txt_TienKhachTra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CHI TIẾT HOÁ ĐƠN");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        pnl_CotTrai.setBackground(new java.awt.Color(255, 255, 255));

        lbl_TieuDe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_TieuDe.setForeground(new java.awt.Color(51, 51, 255));
        lbl_TieuDe.setText("CHI TIẾT HOÁ ĐƠN");

        tbl_DanhSachSanPham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_DanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Mã SP", "Tên SP", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_DanhSachSanPham.setRowHeight(35);
        tbl_DanhSachSanPham.setRowMargin(3);
        jScrollPane2.setViewportView(tbl_DanhSachSanPham);

        javax.swing.GroupLayout pnl_CotTraiLayout = new javax.swing.GroupLayout(pnl_CotTrai);
        pnl_CotTrai.setLayout(pnl_CotTraiLayout);
        pnl_CotTraiLayout.setHorizontalGroup(
            pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                        .addComponent(lbl_TieuDe)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_CotTraiLayout.setVerticalGroup(
            pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TieuDe)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_InHoaDon.setBackground(new java.awt.Color(255, 51, 0));
        btn_InHoaDon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_InHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btn_InHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconPrint.png"))); // NOI18N
        btn_InHoaDon.setText("IN HOÁ ĐƠN");
        btn_InHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_InHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_InHoaDonMouseExited(evt);
            }
        });
        btn_InHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InHoaDonActionPerformed(evt);
            }
        });

        lbl_MaHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_MaHoaDon.setText("Mã hoá đơn");

        txt_MaHoaDon.setEditable(false);
        txt_MaHoaDon.setBackground(new java.awt.Color(255, 255, 204));
        txt_MaHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_MaHoaDon.setFocusable(false);
        txt_MaHoaDon.setRequestFocusEnabled(false);

        txt_TenKhachHang.setEditable(false);
        txt_TenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_TenKhachHang.setFocusable(false);
        txt_TenKhachHang.setRequestFocusEnabled(false);

        lbl_TenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TenKhachHang.setText("Tên khách hàng");

        txt_NhanVien.setEditable(false);
        txt_NhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_NhanVien.setFocusable(false);
        txt_NhanVien.setRequestFocusEnabled(false);

        lbl_NhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NhanVien.setText("Nhân viên");

        lbl_NgayBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NgayBan.setText("Ngày bán");

        txt_NgayBan.setEditable(false);
        txt_NgayBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_NgayBan.setFocusable(false);
        txt_NgayBan.setRequestFocusEnabled(false);

        lbl_TongSoLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TongSoLuong.setText("Tổng số lượng");

        txt_TongSoLuong.setEditable(false);
        txt_TongSoLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_TongSoLuong.setFocusable(false);
        txt_TongSoLuong.setRequestFocusEnabled(false);

        lbl_ThanhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ThanhTien.setText("Thành tiền");

        txt_ThanhTien.setEditable(false);
        txt_ThanhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_ThanhTien.setFocusable(false);
        txt_ThanhTien.setRequestFocusEnabled(false);

        txt_ChietKhau.setEditable(false);
        txt_ChietKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_ChietKhau.setFocusable(false);
        txt_ChietKhau.setRequestFocusEnabled(false);

        lbl_ChietKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ChietKhau.setText("Chiết khấu");

        lbl_VAT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_VAT.setText("VAT");

        txt_VAT.setEditable(false);
        txt_VAT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_VAT.setFocusable(false);
        txt_VAT.setRequestFocusEnabled(false);

        lbl_TongCong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TongCong.setText("Tổng cộng");

        txt_TongCong.setEditable(false);
        txt_TongCong.setBackground(new java.awt.Color(255, 255, 204));
        txt_TongCong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_TongCong.setFocusable(false);
        txt_TongCong.setRequestFocusEnabled(false);

        lbl_TienKhachTra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TienKhachTra.setText("Tiền khách trả");

        txt_TienKhachTra.setEditable(false);
        txt_TienKhachTra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_TienKhachTra.setFocusable(false);
        txt_TienKhachTra.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnl_CotPhaiLayout = new javax.swing.GroupLayout(pnl_CotPhai);
        pnl_CotPhai.setLayout(pnl_CotPhaiLayout);
        pnl_CotPhaiLayout.setHorizontalGroup(
            pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                        .addComponent(lbl_TienKhachTra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_TienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                        .addComponent(lbl_TongCong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_TongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                        .addComponent(lbl_VAT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_VAT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                        .addComponent(lbl_ChietKhau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                        .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                                .addComponent(lbl_ThanhTien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                                .addComponent(lbl_TongSoLuong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_TongSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                                .addComponent(lbl_NgayBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_NgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                                .addComponent(lbl_NhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                                .addComponent(lbl_MaHoaDon)
                                .addGap(51, 51, 51)
                                .addComponent(txt_MaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                                .addComponent(lbl_TenKhachHang)
                                .addGap(18, 18, 18)
                                .addComponent(txt_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(btn_InHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_CotPhaiLayout.setVerticalGroup(
            pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_MaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lbl_MaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TongSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TongSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_VAT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_VAT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TienKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_InHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnl_CotTrai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_CotPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_CotTrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_CotPhai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InHoaDonMouseEntered
        // TODO add your handling code here:
        btn_InHoaDon.setBackground(Color.yellow);
        btn_InHoaDon.setForeground(Color.blue);
        btn_InHoaDon.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_InHoaDonMouseEntered

    private void btn_InHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InHoaDonMouseExited
        // TODO add your handling code here:
        btn_InHoaDon.setBackground(new Color(255, 51, 0));
        btn_InHoaDon.setForeground(Color.white);
    }//GEN-LAST:event_btn_InHoaDonMouseExited

    private void btn_InHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InHoaDonActionPerformed
        // TODO add your handling code here:
        inHoaDon();
    }//GEN-LAST:event_btn_InHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietHoaDonJFrame(HD).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg_LoaiPhieuHuy;
    private javax.swing.JButton btn_InHoaDon;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ChietKhau;
    private javax.swing.JLabel lbl_MaHoaDon;
    private javax.swing.JLabel lbl_NgayBan;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JLabel lbl_TenKhachHang;
    private javax.swing.JLabel lbl_ThanhTien;
    private javax.swing.JLabel lbl_TienKhachTra;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JLabel lbl_TongCong;
    private javax.swing.JLabel lbl_TongSoLuong;
    private javax.swing.JLabel lbl_VAT;
    private javax.swing.JPanel pnl_CotPhai;
    private javax.swing.JPanel pnl_CotTrai;
    private javax.swing.JTable tbl_DanhSachSanPham;
    private javax.swing.JTextField txt_ChietKhau;
    private javax.swing.JTextField txt_MaHoaDon;
    private javax.swing.JTextField txt_NgayBan;
    private javax.swing.JTextField txt_NhanVien;
    private javax.swing.JTextField txt_TenKhachHang;
    private javax.swing.JTextField txt_ThanhTien;
    private javax.swing.JTextField txt_TienKhachTra;
    private javax.swing.JTextField txt_TongCong;
    private javax.swing.JTextField txt_TongSoLuong;
    private javax.swing.JTextField txt_VAT;
    // End of variables declaration//GEN-END:variables

    NhomHangDAO NhomHangDAO = new NhomHangDAO();
    SanPhamDAO SanPhamDAO = new SanPhamDAO();
    DonViTinhDAO DVTDAO = new DonViTinhDAO();
    HoaDonDAO HoaDonDAO = new HoaDonDAO();
    HoaDonChiTietDAO HDCTDAO = new HoaDonChiTietDAO();
    NguoiDungDAO NguoiDungDAO = new NguoiDungDAO();
    KhachHangDAO KhachHangDAO = new KhachHangDAO();
               
    // Định dạng hiển thị số tiền:
    DecimalFormat dcf = new DecimalFormat("###,###,###.###");
    
    /*
     * Hàm khởi tạo các giá trị ban đầu cho JFrame
     */
    void inIt() {
        setTitle("Chi tiết hóa đơn");
        setResizable(false);
        setLocationRelativeTo(null);
        doThongTin();
        doDanhSachSP();
    }
    
    /*
     * Hàm đổ các thông tin mặc định 
     */
    void doThongTin() {
        try {
            // đổ mã hoá đơn
            txt_MaHoaDon.setText(HD.getMaHoaDon());
            // khởi tạo tên khách hàng
            KhachHang KH = KhachHangDAO.timTheoMa(HD.getMaKhachHang());
            txt_TenKhachHang.setText(KH.getHoTen());
            // đổ mã nhân viên
            txt_NhanVien.setText(HD.getMaNhanVien());
            // đổ ngày bán
            txt_NgayBan.setText(DateHelper.toString(HD.getNgayBan(), "dd-MM-yyyy"));
            // đổ tổng số lượng
            txt_TongSoLuong.setText(HD.getTongSoLuong()+"");
            // đổ thành tiền
            float ThanhTien = HoaDonDAO.tinhThanhTien(HD.getMaHoaDon());
            txt_ThanhTien.setText(dcf.format(ThanhTien));
            // đổ chiết khấu
            txt_ChietKhau.setText(dcf.format(HD.getChietKhau()));
            // VAT
            txt_VAT.setText(HD.getVAT()+"");
            // tổng cộng
            txt_TongCong.setText(dcf.format(HD.getThanhTien()));
            // khách trả
            txt_TienKhachTra.setText(dcf.format(HD.getTienKhachTra()));
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }
    
    /*
     * Hàm đổ danh sách sản phẩm trong hoá đơn lên table
     */
    void doDanhSachSP() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tbl_DanhSachSanPham.getModel(); 
            dtm.setRowCount(0);
            List<HoaDonChiTiet> listHDCT = HDCTDAO.timDanhSachHDCT(HD.getMaHoaDon());
            int STT = 1;
            for (HoaDonChiTiet HDCT : listHDCT) {
                SanPham SP = SanPhamDAO.timTheoMaSP(HDCT.getMaSanPham());
                Object[] row = {STT++,
                                HDCT.getMaSanPham(),
                                SP.getTenSanPham(),
                                dcf.format(HDCT.getDonGia()),
                                HDCT.getSoLuong(),
                                dcf.format(HDCT.getThanhTien())};
                dtm.addRow(row);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }
    
    /*
     * Hàm kết nối máy in và in hoá đơn
     */
    void inHoaDon() {
        try {
            HashMap HoaDon = new HashMap();
            HoaDon.put("MaInHoaDon", HD.getMaHoaDon());
            jdbcHelper.inHoaDon(HoaDon);
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }
    
}